apiVersion: kfoundry.io/v1alpha1
kind: Job
metadata:
  generateName: example-job-
  namespace: default
spec:
  script: |
    #!/bin/bash
    echo "Hello, world!"
    hostname
    sleep 100
status: {}
