apiVersion: tenancy.kcp.io/v1alpha1
kind: WorkspaceType
metadata:
  name: jobs
spec:
  extend:
    with:
    - name: universal
      path: root
  defaultAPIBindings:
  - path: root:jobs
    export: kslurm.io
