apiVersion: apis.kcp.io/v1alpha1
kind: APIResourceSchema
metadata:
  creationTimestamp: null
  name: v240427-57d9c7e.jobs.kslurm.io
spec:
  group: kslurm.io
  names:
    kind: Job
    listKind: JobList
    plural: jobs
    singular: job
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      description: Job is the Schema for the jobs API
      properties:
        apiVersion:
          description: |-
            APIVersion defines the versioned schema of this representation of an object.
            Servers should convert recognized schemas to the latest internal value, and
            may reject unrecognized values.
            More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
          type: string
        kind:
          description: |-
            Kind is a string value representing the REST resource this object represents.
            Servers may infer this from the endpoint the client submits requests to.
            Cannot be updated.
            In CamelCase.
            More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
          type: string
        metadata:
          type: object
        spec:
          description: JobSpec defines the desired state of Job
          properties:
            script:
              type: string
          type: object
        status:
          description: JobStatus defines the observed state of Job
          properties:
            id:
              type: integer
          type: object
      type: object
    served: true
    storage: true
    subresources:
      status: {}
