apiVersion: tenancy.kcp.io/v1alpha1
kind: WorkspaceType
metadata:
  name: cluster
spec:
  extend:
    with:
    - name: universal
      path: root
  defaultAPIBindings:
  - path: root:foundry
    export: kfoundry.io
